title: "樽前FM"
email: "takuya.mk96@gmail.com"
description: >
  "苫小牧高専生による雑談Podcast"
baseurl: ""
url: "https://tarumaefm.com"
github_username: tarumaefm
twitter_username: tarumaefm

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Podcast Feed Settings
title: "樽前FM"
email: "takuya.mk96@gmail.com"
description: "苫小牧高専生による雑談Podcastです。学校行事ネタ、ローカルネタの他、アニメやゲーム、ガジェットなど。"
subtitle: "苫小牧高専生による雑談Podcast"
url: "https://tarumaefm.com"
lang: "ja"
author: "Takuya Mukohira"
copyright: "&#xA9; 2016 樽前FM"
keywords: "樽前FM,雑談,高専,苫小牧高専,苫小牧"
